version: "3.7"

services:
  app:
    container_name: api-doeobem
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 8009:80
    environment:
      # Variáveis de ambiente para PHP (opcional, mas recomendado)
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 100M
      PHP_MEMORY_LIMIT: 300M
    depends_on:
      - postgresdb
    networks:
      - api-doeobem

  postgresdb:
    container_name: postgresdb
    image: postgres:17
    restart: unless-stopped
    shm_size: 1G
    environment:
      POSTGRES_DB: api-doeobem
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_ROOT_PASSWORD: 123
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - api-doeobem

networks:
  api-doeobem:
    name: api-doeobem
    driver: bridge