version: "3.7"

services:

  app:
    container_name: api-doeobem
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 8009:80

  mysqlslim:
    container_name: mysqlslim
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: api-doeobem
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_USER: root
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - 3308:3306

  phpmyadminslim:
      image: phpmyadmin/phpmyadmin
      restart: unless-stopped
      ports:
        - "8090:80"
      environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
          MYSQL_ROOT_PASSWORD: 123